name: .NET Core

on:
  workflow_run:
    workflows: ["tests"]
    branches: [master]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.*'

      - name: Nuget pack (github)
        run:  dotnet pack -c Release -o out

      - name: Push nuget (github)
        run: dotnet nuget push ./out/*.nupkg --api-key "${{ secrets.NUGETKEY }}" -s https://api.nuget.org/v3/index.json --skip-duplicate
